apiVersion: v1
kind: Pod
metadata:
  name: emptydir-memory
spec:
  containers:
  - name: test
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - mountPath: /cache
      name: cache-vol

  volumes:
  - name: cache-vol
    emptyDir:
      medium: Memory
